# Generated by Django 5.2.3 on 2025-07-07 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
    ]
